/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutContent {
  'coreValues' : Array<CoreValue>,
  'organizationStory' : string,
}
export interface AddBlogPostRequest {
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'tags' : Array<string>,
  'featuredImageUrl' : [] | [string],
  'category' : string,
}
export interface AddDocumentRequest {
  'title' : string,
  'description' : string,
  'category' : DocumentCategory,
  'fileUrl' : string,
}
export interface AddEventRequest {
  'title' : string,
  'isCompleted' : boolean,
  'date' : bigint,
  'isRegistrationOpen' : boolean,
  'description' : string,
  'featuredImageUrl' : [] | [string],
  'location' : string,
}
export interface AddGalleryItemRequest {
  'url' : string,
  'title' : [] | [string],
  'blob' : [] | [ExternalBlob],
  'description' : [] | [string],
  'mediaType' : MediaType,
  'category' : GalleryCategory,
}
export interface AddImpactReportRequest {
  'media' : Array<ImpactMedia>,
  'title' : string,
  'volunteerCount' : bigint,
  'description' : string,
  'reportDate' : bigint,
  'areasCoovered' : bigint,
  'resolvedCases' : bigint,
}
export interface AddProjectRequest {
  'status' : ProjectStatus,
  'title' : string,
  'description' : string,
  'progressPercent' : bigint,
  'featuredImageUrl' : [] | [string],
  'category' : string,
}
export interface AddTeamMemberRequest {
  'bio' : [] | [string],
  'order' : bigint,
  'name' : string,
  'role' : string,
  'photoUrl' : [] | [string],
}
export interface AddTestimonialRequest {
  'name' : string,
  'role' : string,
  'quote' : string,
  'photoUrl' : [] | [string],
  'isActive' : boolean,
}
export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'featuredImageUrl' : [] | [string],
  'category' : string,
}
export interface CoreValue { 'title' : string, 'description' : string }
export interface Document {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'category' : DocumentCategory,
  'fileUrl' : string,
}
export type DocumentCategory = { 'certificate' : null } |
  { 'other' : null } |
  { 'legal' : null } |
  { 'auditReport' : null } |
  { 'annualReport' : null } |
  { 'policy' : null };
export interface EditReportRequest {
  'id' : string,
  'imageBlob' : [] | [ExternalBlob],
  'name' : [] | [string],
  'description' : [] | [string],
  'district' : [] | [string],
  'category' : [] | [ReportCategory],
  'mobile' : [] | [string],
  'location' : [] | [string],
}
export interface Event {
  'id' : string,
  'title' : string,
  'isCompleted' : boolean,
  'date' : bigint,
  'isRegistrationOpen' : boolean,
  'createdAt' : bigint,
  'description' : string,
  'featuredImageUrl' : [] | [string],
  'location' : string,
}
export interface EventRegistration {
  'id' : string,
  'eventId' : string,
  'name' : string,
  'createdAt' : bigint,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export type GalleryCategory = { 'general' : null } |
  { 'donor' : null };
export interface GalleryItem {
  'id' : string,
  'url' : string,
  'title' : [] | [string],
  'blob' : [] | [ExternalBlob],
  'createdAt' : bigint,
  'description' : [] | [string],
  'updatedAt' : bigint,
  'mediaType' : MediaType,
  'category' : GalleryCategory,
}
export interface HomeContent {
  'missionText' : string,
  'ctaButtonLink' : string,
  'ctaButtonText' : string,
  'heroSubtitle' : string,
  'heroTitle' : string,
  'visionText' : string,
}
export interface ImpactMedia {
  'url' : string,
  'blob' : [] | [ExternalBlob],
  'mediaType' : { 'video' : null } |
    { 'image' : null },
}
export interface ImpactReport {
  'id' : string,
  'media' : Array<ImpactMedia>,
  'title' : string,
  'volunteerCount' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'reportDate' : bigint,
  'updatedAt' : bigint,
  'areasCoovered' : bigint,
  'resolvedCases' : bigint,
}
export type MediaType = { 'video' : null } |
  { 'image' : null };
export interface Project {
  'id' : string,
  'status' : ProjectStatus,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'progressPercent' : bigint,
  'featuredImageUrl' : [] | [string],
  'category' : string,
}
export type ProjectStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'planning' : null };
export interface RegisterForEventRequest {
  'eventId' : string,
  'name' : string,
  'phone' : string,
}
export interface Report {
  'id' : string,
  'status' : ReportStatus,
  'imageBlob' : [] | [ExternalBlob],
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'district' : string,
  'updatedAt' : bigint,
  'category' : ReportCategory,
  'mobile' : string,
  'location' : string,
  'refNumber' : string,
}
export type ReportCategory = { 'other' : null } |
  { 'roadCleanliness' : null } |
  { 'garbage' : null } |
  { 'waterLogging' : null } |
  { 'publicToiletIssue' : null } |
  { 'drainageIssue' : null };
export type ReportStatus = { 'resolved' : null } |
  { 'pending' : null };
export interface Settings {
  'bankAccountNumber' : [] | [string],
  'websiteName' : string,
  'bankAccountHolder' : [] | [string],
  'founderName' : [] | [string],
  'founderPhoto' : [] | [string],
  'socialLinks' : SocialLinks,
  'bankIfsc' : [] | [string],
  'whatsappNumber' : string,
  'founderBio' : [] | [string],
  'upiQrImageUrl' : [] | [string],
  'contactEmail' : string,
  'upiId' : [] | [string],
  'location' : string,
  'contactPhone' : string,
}
export interface SocialLinks {
  'twitter' : [] | [string],
  'instagram' : [] | [string],
  'facebook' : [] | [string],
  'youtube' : [] | [string],
}
export interface Stats {
  'resolved' : bigint,
  'total' : bigint,
  'pending' : bigint,
  'volunteers' : bigint,
}
export interface SubmitReportRequest {
  'imageBlob' : [] | [ExternalBlob],
  'name' : string,
  'description' : string,
  'district' : string,
  'category' : ReportCategory,
  'mobile' : string,
  'location' : string,
}
export interface TeamMember {
  'id' : string,
  'bio' : [] | [string],
  'order' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'role' : string,
  'photoUrl' : [] | [string],
  'updatedAt' : bigint,
}
export interface Testimonial {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'role' : string,
  'quote' : string,
  'photoUrl' : [] | [string],
  'isActive' : boolean,
}
export type Timestamp = bigint;
export interface UpdateBlogPostRequest {
  'id' : string,
  'title' : [] | [string],
  'content' : [] | [string],
  'isPublished' : [] | [boolean],
  'tags' : [] | [Array<string>],
  'featuredImageUrl' : [] | [string],
  'category' : [] | [string],
}
export interface UpdateEventRequest {
  'id' : string,
  'title' : [] | [string],
  'isCompleted' : [] | [boolean],
  'date' : [] | [bigint],
  'isRegistrationOpen' : [] | [boolean],
  'description' : [] | [string],
  'featuredImageUrl' : [] | [string],
  'location' : [] | [string],
}
export interface UpdateGalleryItemRequest {
  'id' : string,
  'url' : [] | [string],
  'title' : [] | [string],
  'blob' : [] | [ExternalBlob],
  'description' : [] | [string],
  'category' : [] | [GalleryCategory],
}
export interface UpdateImpactReportRequest {
  'id' : string,
  'media' : [] | [Array<ImpactMedia>],
  'title' : [] | [string],
  'volunteerCount' : [] | [bigint],
  'description' : [] | [string],
  'reportDate' : [] | [bigint],
  'areasCoovered' : [] | [bigint],
  'resolvedCases' : [] | [bigint],
}
export interface UpdateProjectRequest {
  'id' : string,
  'status' : [] | [ProjectStatus],
  'title' : [] | [string],
  'description' : [] | [string],
  'progressPercent' : [] | [bigint],
  'featuredImageUrl' : [] | [string],
  'category' : [] | [string],
}
export interface UpdateTeamMemberRequest {
  'id' : string,
  'bio' : [] | [string],
  'order' : [] | [bigint],
  'name' : [] | [string],
  'role' : [] | [string],
  'photoUrl' : [] | [string],
}
export interface UpdateTestimonialRequest {
  'id' : string,
  'name' : [] | [string],
  'role' : [] | [string],
  'quote' : [] | [string],
  'photoUrl' : [] | [string],
  'isActive' : [] | [boolean],
}
export interface User {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'photoUrl' : string,
  'email' : string,
}
export type UserId = string;
export interface VolunteerApplication {
  'id' : string,
  'status' : VolunteerStatus,
  'volunteerHours' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'availability' : string,
  'rankingBadge' : string,
  'mobile' : string,
}
export type VolunteerStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addBlogPost' : ActorMethod<[AddBlogPostRequest], BlogPost>,
  'addDocument' : ActorMethod<[AddDocumentRequest], Document>,
  'addEvent' : ActorMethod<[AddEventRequest], Event>,
  'addGalleryItem' : ActorMethod<
    [string, AddGalleryItemRequest],
    [] | [GalleryItem]
  >,
  'addImpactReport' : ActorMethod<
    [string, AddImpactReportRequest],
    [] | [ImpactReport]
  >,
  'addProject' : ActorMethod<[AddProjectRequest], Project>,
  'addTeamMember' : ActorMethod<
    [string, AddTeamMemberRequest],
    [] | [TeamMember]
  >,
  'addTestimonial' : ActorMethod<[AddTestimonialRequest], Testimonial>,
  'adminLogin' : ActorMethod<[string, string], [] | [string]>,
  'adminLogout' : ActorMethod<[string], boolean>,
  'deleteBlogPost' : ActorMethod<[string], boolean>,
  'deleteDocument' : ActorMethod<[string], boolean>,
  'deleteEvent' : ActorMethod<[string], boolean>,
  'deleteGalleryItem' : ActorMethod<[string, string], boolean>,
  'deleteImpactReport' : ActorMethod<[string, string], boolean>,
  'deleteProject' : ActorMethod<[string], boolean>,
  'deleteReport' : ActorMethod<[string], boolean>,
  'deleteTeamMember' : ActorMethod<[string, string], boolean>,
  'deleteTestimonial' : ActorMethod<[string], boolean>,
  'deleteUser' : ActorMethod<[string], boolean>,
  'deleteVolunteerApplication' : ActorMethod<[string], boolean>,
  'editReport' : ActorMethod<[EditReportRequest], [] | [Report]>,
  'getAboutContent' : ActorMethod<[], AboutContent>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getBlogPost' : ActorMethod<[string], [] | [BlogPost]>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getDocuments' : ActorMethod<[], Array<Document>>,
  'getDonorGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getEventRegistrations' : ActorMethod<[string], Array<EventRegistration>>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getHomeContent' : ActorMethod<[], HomeContent>,
  'getImpactReport' : ActorMethod<[string], [] | [ImpactReport]>,
  'getImpactReports' : ActorMethod<[], Array<ImpactReport>>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getPublicGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getReport' : ActorMethod<[string], [] | [Report]>,
  'getReports' : ActorMethod<[], Array<Report>>,
  'getSettings' : ActorMethod<[], Settings>,
  'getStats' : ActorMethod<[], Stats>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserById' : ActorMethod<[string], [] | [User]>,
  'getVolunteerApplications' : ActorMethod<[], Array<VolunteerApplication>>,
  'registerForEvent' : ActorMethod<
    [RegisterForEventRequest],
    EventRegistration
  >,
  'registerOrUpdateUser' : ActorMethod<[User], User>,
  'saveSettings' : ActorMethod<[string, Settings], boolean>,
  'submitReport' : ActorMethod<[SubmitReportRequest], Report>,
  'submitVolunteerApplication' : ActorMethod<
    [string, string, string, string],
    VolunteerApplication
  >,
  'updateAboutContent' : ActorMethod<[AboutContent], boolean>,
  'updateBlogPost' : ActorMethod<[UpdateBlogPostRequest], [] | [BlogPost]>,
  'updateEvent' : ActorMethod<[UpdateEventRequest], [] | [Event]>,
  'updateGalleryItem' : ActorMethod<
    [string, UpdateGalleryItemRequest],
    [] | [GalleryItem]
  >,
  'updateHomeContent' : ActorMethod<[HomeContent], boolean>,
  'updateImpactReport' : ActorMethod<
    [string, UpdateImpactReportRequest],
    [] | [ImpactReport]
  >,
  'updateProject' : ActorMethod<[UpdateProjectRequest], [] | [Project]>,
  'updateReportStatus' : ActorMethod<[string, ReportStatus], boolean>,
  'updateTeamMember' : ActorMethod<
    [string, UpdateTeamMemberRequest],
    [] | [TeamMember]
  >,
  'updateTestimonial' : ActorMethod<
    [UpdateTestimonialRequest],
    [] | [Testimonial]
  >,
  'updateVolunteerHours' : ActorMethod<[string, bigint], boolean>,
  'updateVolunteerStatus' : ActorMethod<[string, VolunteerStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];