/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AddBlogPostRequest = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
});
export const DocumentCategory = IDL.Variant({
  'certificate' : IDL.Null,
  'other' : IDL.Null,
  'legal' : IDL.Null,
  'auditReport' : IDL.Null,
  'annualReport' : IDL.Null,
  'policy' : IDL.Null,
});
export const AddDocumentRequest = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : DocumentCategory,
  'fileUrl' : IDL.Text,
});
export const Document = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : DocumentCategory,
  'fileUrl' : IDL.Text,
});
export const AddEventRequest = IDL.Record({
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'date' : IDL.Int,
  'isRegistrationOpen' : IDL.Bool,
  'description' : IDL.Text,
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'date' : IDL.Int,
  'isRegistrationOpen' : IDL.Bool,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaType = IDL.Variant({
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const GalleryCategory = IDL.Variant({
  'general' : IDL.Null,
  'donor' : IDL.Null,
});
export const AddGalleryItemRequest = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Opt(IDL.Text),
  'blob' : IDL.Opt(ExternalBlob),
  'description' : IDL.Opt(IDL.Text),
  'mediaType' : MediaType,
  'category' : GalleryCategory,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Opt(IDL.Text),
  'blob' : IDL.Opt(ExternalBlob),
  'createdAt' : IDL.Int,
  'description' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'mediaType' : MediaType,
  'category' : GalleryCategory,
});
export const ImpactMedia = IDL.Record({
  'url' : IDL.Text,
  'blob' : IDL.Opt(ExternalBlob),
  'mediaType' : IDL.Variant({ 'video' : IDL.Null, 'image' : IDL.Null }),
});
export const AddImpactReportRequest = IDL.Record({
  'media' : IDL.Vec(ImpactMedia),
  'title' : IDL.Text,
  'volunteerCount' : IDL.Nat,
  'description' : IDL.Text,
  'reportDate' : IDL.Int,
  'areasCoovered' : IDL.Nat,
  'resolvedCases' : IDL.Nat,
});
export const ImpactReport = IDL.Record({
  'id' : IDL.Text,
  'media' : IDL.Vec(ImpactMedia),
  'title' : IDL.Text,
  'volunteerCount' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'reportDate' : IDL.Int,
  'updatedAt' : IDL.Int,
  'areasCoovered' : IDL.Nat,
  'resolvedCases' : IDL.Nat,
});
export const ProjectStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'planning' : IDL.Null,
});
export const AddProjectRequest = IDL.Record({
  'status' : ProjectStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'progressPercent' : IDL.Nat,
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'status' : ProjectStatus,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'progressPercent' : IDL.Nat,
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
});
export const AddTeamMemberRequest = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
});
export const TeamMember = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Opt(IDL.Text),
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
});
export const AddTestimonialRequest = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'quote' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'quote' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
});
export const ReportCategory = IDL.Variant({
  'other' : IDL.Null,
  'roadCleanliness' : IDL.Null,
  'garbage' : IDL.Null,
  'waterLogging' : IDL.Null,
  'publicToiletIssue' : IDL.Null,
  'drainageIssue' : IDL.Null,
});
export const EditReportRequest = IDL.Record({
  'id' : IDL.Text,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'name' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'district' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(ReportCategory),
  'mobile' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const ReportStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'pending' : IDL.Null,
});
export const Report = IDL.Record({
  'id' : IDL.Text,
  'status' : ReportStatus,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'district' : IDL.Text,
  'updatedAt' : IDL.Int,
  'category' : ReportCategory,
  'mobile' : IDL.Text,
  'location' : IDL.Text,
  'refNumber' : IDL.Text,
});
export const CoreValue = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const AboutContent = IDL.Record({
  'coreValues' : IDL.Vec(CoreValue),
  'organizationStory' : IDL.Text,
});
export const UserId = IDL.Text;
export const Timestamp = IDL.Int;
export const User = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'photoUrl' : IDL.Text,
  'email' : IDL.Text,
});
export const EventRegistration = IDL.Record({
  'id' : IDL.Text,
  'eventId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'phone' : IDL.Text,
});
export const HomeContent = IDL.Record({
  'missionText' : IDL.Text,
  'ctaButtonLink' : IDL.Text,
  'ctaButtonText' : IDL.Text,
  'heroSubtitle' : IDL.Text,
  'heroTitle' : IDL.Text,
  'visionText' : IDL.Text,
});
export const SocialLinks = IDL.Record({
  'twitter' : IDL.Opt(IDL.Text),
  'instagram' : IDL.Opt(IDL.Text),
  'facebook' : IDL.Opt(IDL.Text),
  'youtube' : IDL.Opt(IDL.Text),
});
export const Settings = IDL.Record({
  'bankAccountNumber' : IDL.Opt(IDL.Text),
  'websiteName' : IDL.Text,
  'bankAccountHolder' : IDL.Opt(IDL.Text),
  'founderName' : IDL.Opt(IDL.Text),
  'founderPhoto' : IDL.Opt(IDL.Text),
  'socialLinks' : SocialLinks,
  'bankIfsc' : IDL.Opt(IDL.Text),
  'whatsappNumber' : IDL.Text,
  'founderBio' : IDL.Opt(IDL.Text),
  'upiQrImageUrl' : IDL.Opt(IDL.Text),
  'contactEmail' : IDL.Text,
  'upiId' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const Stats = IDL.Record({
  'resolved' : IDL.Nat,
  'total' : IDL.Nat,
  'pending' : IDL.Nat,
  'volunteers' : IDL.Nat,
});
export const VolunteerStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const VolunteerApplication = IDL.Record({
  'id' : IDL.Text,
  'status' : VolunteerStatus,
  'volunteerHours' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'availability' : IDL.Text,
  'rankingBadge' : IDL.Text,
  'mobile' : IDL.Text,
});
export const RegisterForEventRequest = IDL.Record({
  'eventId' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const SubmitReportRequest = IDL.Record({
  'imageBlob' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'district' : IDL.Text,
  'category' : ReportCategory,
  'mobile' : IDL.Text,
  'location' : IDL.Text,
});
export const UpdateBlogPostRequest = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Opt(IDL.Text),
  'content' : IDL.Opt(IDL.Text),
  'isPublished' : IDL.Opt(IDL.Bool),
  'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
});
export const UpdateEventRequest = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Opt(IDL.Text),
  'isCompleted' : IDL.Opt(IDL.Bool),
  'date' : IDL.Opt(IDL.Int),
  'isRegistrationOpen' : IDL.Opt(IDL.Bool),
  'description' : IDL.Opt(IDL.Text),
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const UpdateGalleryItemRequest = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Opt(IDL.Text),
  'title' : IDL.Opt(IDL.Text),
  'blob' : IDL.Opt(ExternalBlob),
  'description' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(GalleryCategory),
});
export const UpdateImpactReportRequest = IDL.Record({
  'id' : IDL.Text,
  'media' : IDL.Opt(IDL.Vec(ImpactMedia)),
  'title' : IDL.Opt(IDL.Text),
  'volunteerCount' : IDL.Opt(IDL.Nat),
  'description' : IDL.Opt(IDL.Text),
  'reportDate' : IDL.Opt(IDL.Int),
  'areasCoovered' : IDL.Opt(IDL.Nat),
  'resolvedCases' : IDL.Opt(IDL.Nat),
});
export const UpdateProjectRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Opt(ProjectStatus),
  'title' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'progressPercent' : IDL.Opt(IDL.Nat),
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
});
export const UpdateTeamMemberRequest = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Opt(IDL.Text),
  'order' : IDL.Opt(IDL.Nat),
  'name' : IDL.Opt(IDL.Text),
  'role' : IDL.Opt(IDL.Text),
  'photoUrl' : IDL.Opt(IDL.Text),
});
export const UpdateTestimonialRequest = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Opt(IDL.Text),
  'role' : IDL.Opt(IDL.Text),
  'quote' : IDL.Opt(IDL.Text),
  'photoUrl' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Opt(IDL.Bool),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addBlogPost' : IDL.Func([AddBlogPostRequest], [BlogPost], []),
  'addDocument' : IDL.Func([AddDocumentRequest], [Document], []),
  'addEvent' : IDL.Func([AddEventRequest], [Event], []),
  'addGalleryItem' : IDL.Func(
      [IDL.Text, AddGalleryItemRequest],
      [IDL.Opt(GalleryItem)],
      [],
    ),
  'addImpactReport' : IDL.Func(
      [IDL.Text, AddImpactReportRequest],
      [IDL.Opt(ImpactReport)],
      [],
    ),
  'addProject' : IDL.Func([AddProjectRequest], [Project], []),
  'addTeamMember' : IDL.Func(
      [IDL.Text, AddTeamMemberRequest],
      [IDL.Opt(TeamMember)],
      [],
    ),
  'addTestimonial' : IDL.Func([AddTestimonialRequest], [Testimonial], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
  'adminLogout' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteDocument' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteEvent' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteGalleryItem' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteImpactReport' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteProject' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteReport' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteTeamMember' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteTestimonial' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteVolunteerApplication' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'editReport' : IDL.Func([EditReportRequest], [IDL.Opt(Report)], []),
  'getAboutContent' : IDL.Func([], [AboutContent], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], []),
  'getDocuments' : IDL.Func([], [IDL.Vec(Document)], []),
  'getDonorGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getEventRegistrations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EventRegistration)],
      [],
    ),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], []),
  'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getHomeContent' : IDL.Func([], [HomeContent], ['query']),
  'getImpactReport' : IDL.Func([IDL.Text], [IDL.Opt(ImpactReport)], ['query']),
  'getImpactReports' : IDL.Func([], [IDL.Vec(ImpactReport)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], []),
  'getPublicGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getReport' : IDL.Func([IDL.Text], [IDL.Opt(Report)], ['query']),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], []),
  'getUserById' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getVolunteerApplications' : IDL.Func(
      [],
      [IDL.Vec(VolunteerApplication)],
      ['query'],
    ),
  'registerForEvent' : IDL.Func(
      [RegisterForEventRequest],
      [EventRegistration],
      [],
    ),
  'registerOrUpdateUser' : IDL.Func([User], [User], []),
  'saveSettings' : IDL.Func([IDL.Text, Settings], [IDL.Bool], []),
  'submitReport' : IDL.Func([SubmitReportRequest], [Report], []),
  'submitVolunteerApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [VolunteerApplication],
      [],
    ),
  'updateAboutContent' : IDL.Func([AboutContent], [IDL.Bool], []),
  'updateBlogPost' : IDL.Func([UpdateBlogPostRequest], [IDL.Opt(BlogPost)], []),
  'updateEvent' : IDL.Func([UpdateEventRequest], [IDL.Opt(Event)], []),
  'updateGalleryItem' : IDL.Func(
      [IDL.Text, UpdateGalleryItemRequest],
      [IDL.Opt(GalleryItem)],
      [],
    ),
  'updateHomeContent' : IDL.Func([HomeContent], [IDL.Bool], []),
  'updateImpactReport' : IDL.Func(
      [IDL.Text, UpdateImpactReportRequest],
      [IDL.Opt(ImpactReport)],
      [],
    ),
  'updateProject' : IDL.Func([UpdateProjectRequest], [IDL.Opt(Project)], []),
  'updateReportStatus' : IDL.Func([IDL.Text, ReportStatus], [IDL.Bool], []),
  'updateTeamMember' : IDL.Func(
      [IDL.Text, UpdateTeamMemberRequest],
      [IDL.Opt(TeamMember)],
      [],
    ),
  'updateTestimonial' : IDL.Func(
      [UpdateTestimonialRequest],
      [IDL.Opt(Testimonial)],
      [],
    ),
  'updateVolunteerHours' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'updateVolunteerStatus' : IDL.Func(
      [IDL.Text, VolunteerStatus],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AddBlogPostRequest = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
  });
  const DocumentCategory = IDL.Variant({
    'certificate' : IDL.Null,
    'other' : IDL.Null,
    'legal' : IDL.Null,
    'auditReport' : IDL.Null,
    'annualReport' : IDL.Null,
    'policy' : IDL.Null,
  });
  const AddDocumentRequest = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : DocumentCategory,
    'fileUrl' : IDL.Text,
  });
  const Document = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : DocumentCategory,
    'fileUrl' : IDL.Text,
  });
  const AddEventRequest = IDL.Record({
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'date' : IDL.Int,
    'isRegistrationOpen' : IDL.Bool,
    'description' : IDL.Text,
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'date' : IDL.Int,
    'isRegistrationOpen' : IDL.Bool,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaType = IDL.Variant({ 'video' : IDL.Null, 'image' : IDL.Null });
  const GalleryCategory = IDL.Variant({
    'general' : IDL.Null,
    'donor' : IDL.Null,
  });
  const AddGalleryItemRequest = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Opt(IDL.Text),
    'blob' : IDL.Opt(ExternalBlob),
    'description' : IDL.Opt(IDL.Text),
    'mediaType' : MediaType,
    'category' : GalleryCategory,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Opt(IDL.Text),
    'blob' : IDL.Opt(ExternalBlob),
    'createdAt' : IDL.Int,
    'description' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'mediaType' : MediaType,
    'category' : GalleryCategory,
  });
  const ImpactMedia = IDL.Record({
    'url' : IDL.Text,
    'blob' : IDL.Opt(ExternalBlob),
    'mediaType' : IDL.Variant({ 'video' : IDL.Null, 'image' : IDL.Null }),
  });
  const AddImpactReportRequest = IDL.Record({
    'media' : IDL.Vec(ImpactMedia),
    'title' : IDL.Text,
    'volunteerCount' : IDL.Nat,
    'description' : IDL.Text,
    'reportDate' : IDL.Int,
    'areasCoovered' : IDL.Nat,
    'resolvedCases' : IDL.Nat,
  });
  const ImpactReport = IDL.Record({
    'id' : IDL.Text,
    'media' : IDL.Vec(ImpactMedia),
    'title' : IDL.Text,
    'volunteerCount' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'reportDate' : IDL.Int,
    'updatedAt' : IDL.Int,
    'areasCoovered' : IDL.Nat,
    'resolvedCases' : IDL.Nat,
  });
  const ProjectStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'planning' : IDL.Null,
  });
  const AddProjectRequest = IDL.Record({
    'status' : ProjectStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'progressPercent' : IDL.Nat,
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'status' : ProjectStatus,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'progressPercent' : IDL.Nat,
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
  });
  const AddTeamMemberRequest = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Opt(IDL.Text),
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
  });
  const AddTestimonialRequest = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'quote' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'quote' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
  });
  const ReportCategory = IDL.Variant({
    'other' : IDL.Null,
    'roadCleanliness' : IDL.Null,
    'garbage' : IDL.Null,
    'waterLogging' : IDL.Null,
    'publicToiletIssue' : IDL.Null,
    'drainageIssue' : IDL.Null,
  });
  const EditReportRequest = IDL.Record({
    'id' : IDL.Text,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'name' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'district' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(ReportCategory),
    'mobile' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const ReportStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
  });
  const Report = IDL.Record({
    'id' : IDL.Text,
    'status' : ReportStatus,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'district' : IDL.Text,
    'updatedAt' : IDL.Int,
    'category' : ReportCategory,
    'mobile' : IDL.Text,
    'location' : IDL.Text,
    'refNumber' : IDL.Text,
  });
  const CoreValue = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const AboutContent = IDL.Record({
    'coreValues' : IDL.Vec(CoreValue),
    'organizationStory' : IDL.Text,
  });
  const UserId = IDL.Text;
  const Timestamp = IDL.Int;
  const User = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'photoUrl' : IDL.Text,
    'email' : IDL.Text,
  });
  const EventRegistration = IDL.Record({
    'id' : IDL.Text,
    'eventId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'phone' : IDL.Text,
  });
  const HomeContent = IDL.Record({
    'missionText' : IDL.Text,
    'ctaButtonLink' : IDL.Text,
    'ctaButtonText' : IDL.Text,
    'heroSubtitle' : IDL.Text,
    'heroTitle' : IDL.Text,
    'visionText' : IDL.Text,
  });
  const SocialLinks = IDL.Record({
    'twitter' : IDL.Opt(IDL.Text),
    'instagram' : IDL.Opt(IDL.Text),
    'facebook' : IDL.Opt(IDL.Text),
    'youtube' : IDL.Opt(IDL.Text),
  });
  const Settings = IDL.Record({
    'bankAccountNumber' : IDL.Opt(IDL.Text),
    'websiteName' : IDL.Text,
    'bankAccountHolder' : IDL.Opt(IDL.Text),
    'founderName' : IDL.Opt(IDL.Text),
    'founderPhoto' : IDL.Opt(IDL.Text),
    'socialLinks' : SocialLinks,
    'bankIfsc' : IDL.Opt(IDL.Text),
    'whatsappNumber' : IDL.Text,
    'founderBio' : IDL.Opt(IDL.Text),
    'upiQrImageUrl' : IDL.Opt(IDL.Text),
    'contactEmail' : IDL.Text,
    'upiId' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const Stats = IDL.Record({
    'resolved' : IDL.Nat,
    'total' : IDL.Nat,
    'pending' : IDL.Nat,
    'volunteers' : IDL.Nat,
  });
  const VolunteerStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const VolunteerApplication = IDL.Record({
    'id' : IDL.Text,
    'status' : VolunteerStatus,
    'volunteerHours' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'availability' : IDL.Text,
    'rankingBadge' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const RegisterForEventRequest = IDL.Record({
    'eventId' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SubmitReportRequest = IDL.Record({
    'imageBlob' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'district' : IDL.Text,
    'category' : ReportCategory,
    'mobile' : IDL.Text,
    'location' : IDL.Text,
  });
  const UpdateBlogPostRequest = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Opt(IDL.Text),
    'content' : IDL.Opt(IDL.Text),
    'isPublished' : IDL.Opt(IDL.Bool),
    'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
  });
  const UpdateEventRequest = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Opt(IDL.Text),
    'isCompleted' : IDL.Opt(IDL.Bool),
    'date' : IDL.Opt(IDL.Int),
    'isRegistrationOpen' : IDL.Opt(IDL.Bool),
    'description' : IDL.Opt(IDL.Text),
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const UpdateGalleryItemRequest = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Opt(IDL.Text),
    'title' : IDL.Opt(IDL.Text),
    'blob' : IDL.Opt(ExternalBlob),
    'description' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(GalleryCategory),
  });
  const UpdateImpactReportRequest = IDL.Record({
    'id' : IDL.Text,
    'media' : IDL.Opt(IDL.Vec(ImpactMedia)),
    'title' : IDL.Opt(IDL.Text),
    'volunteerCount' : IDL.Opt(IDL.Nat),
    'description' : IDL.Opt(IDL.Text),
    'reportDate' : IDL.Opt(IDL.Int),
    'areasCoovered' : IDL.Opt(IDL.Nat),
    'resolvedCases' : IDL.Opt(IDL.Nat),
  });
  const UpdateProjectRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Opt(ProjectStatus),
    'title' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'progressPercent' : IDL.Opt(IDL.Nat),
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
  });
  const UpdateTeamMemberRequest = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Opt(IDL.Text),
    'order' : IDL.Opt(IDL.Nat),
    'name' : IDL.Opt(IDL.Text),
    'role' : IDL.Opt(IDL.Text),
    'photoUrl' : IDL.Opt(IDL.Text),
  });
  const UpdateTestimonialRequest = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Opt(IDL.Text),
    'role' : IDL.Opt(IDL.Text),
    'quote' : IDL.Opt(IDL.Text),
    'photoUrl' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Opt(IDL.Bool),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addBlogPost' : IDL.Func([AddBlogPostRequest], [BlogPost], []),
    'addDocument' : IDL.Func([AddDocumentRequest], [Document], []),
    'addEvent' : IDL.Func([AddEventRequest], [Event], []),
    'addGalleryItem' : IDL.Func(
        [IDL.Text, AddGalleryItemRequest],
        [IDL.Opt(GalleryItem)],
        [],
      ),
    'addImpactReport' : IDL.Func(
        [IDL.Text, AddImpactReportRequest],
        [IDL.Opt(ImpactReport)],
        [],
      ),
    'addProject' : IDL.Func([AddProjectRequest], [Project], []),
    'addTeamMember' : IDL.Func(
        [IDL.Text, AddTeamMemberRequest],
        [IDL.Opt(TeamMember)],
        [],
      ),
    'addTestimonial' : IDL.Func([AddTestimonialRequest], [Testimonial], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
    'adminLogout' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteDocument' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteEvent' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteGalleryItem' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteImpactReport' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteProject' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteReport' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteTeamMember' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteTestimonial' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteVolunteerApplication' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'editReport' : IDL.Func([EditReportRequest], [IDL.Opt(Report)], []),
    'getAboutContent' : IDL.Func([], [AboutContent], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], []),
    'getDocuments' : IDL.Func([], [IDL.Vec(Document)], []),
    'getDonorGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getEventRegistrations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EventRegistration)],
        [],
      ),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], []),
    'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getHomeContent' : IDL.Func([], [HomeContent], ['query']),
    'getImpactReport' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ImpactReport)],
        ['query'],
      ),
    'getImpactReports' : IDL.Func([], [IDL.Vec(ImpactReport)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], []),
    'getPublicGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getReport' : IDL.Func([IDL.Text], [IDL.Opt(Report)], ['query']),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], []),
    'getUserById' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getVolunteerApplications' : IDL.Func(
        [],
        [IDL.Vec(VolunteerApplication)],
        ['query'],
      ),
    'registerForEvent' : IDL.Func(
        [RegisterForEventRequest],
        [EventRegistration],
        [],
      ),
    'registerOrUpdateUser' : IDL.Func([User], [User], []),
    'saveSettings' : IDL.Func([IDL.Text, Settings], [IDL.Bool], []),
    'submitReport' : IDL.Func([SubmitReportRequest], [Report], []),
    'submitVolunteerApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [VolunteerApplication],
        [],
      ),
    'updateAboutContent' : IDL.Func([AboutContent], [IDL.Bool], []),
    'updateBlogPost' : IDL.Func(
        [UpdateBlogPostRequest],
        [IDL.Opt(BlogPost)],
        [],
      ),
    'updateEvent' : IDL.Func([UpdateEventRequest], [IDL.Opt(Event)], []),
    'updateGalleryItem' : IDL.Func(
        [IDL.Text, UpdateGalleryItemRequest],
        [IDL.Opt(GalleryItem)],
        [],
      ),
    'updateHomeContent' : IDL.Func([HomeContent], [IDL.Bool], []),
    'updateImpactReport' : IDL.Func(
        [IDL.Text, UpdateImpactReportRequest],
        [IDL.Opt(ImpactReport)],
        [],
      ),
    'updateProject' : IDL.Func([UpdateProjectRequest], [IDL.Opt(Project)], []),
    'updateReportStatus' : IDL.Func([IDL.Text, ReportStatus], [IDL.Bool], []),
    'updateTeamMember' : IDL.Func(
        [IDL.Text, UpdateTeamMemberRequest],
        [IDL.Opt(TeamMember)],
        [],
      ),
    'updateTestimonial' : IDL.Func(
        [UpdateTestimonialRequest],
        [IDL.Opt(Testimonial)],
        [],
      ),
    'updateVolunteerHours' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'updateVolunteerStatus' : IDL.Func(
        [IDL.Text, VolunteerStatus],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };